[workspace.package]
name = "interconnect"
description = "High performance inter-process communication protocol"
repository = "https://github.com/geo-mak/interconnect"
license-file = "LICENSE"

rust-version = "1.94.1"
edition = "2024"

[workspace]
members = ["ic_runtime", "ic_compiler"]
resolver = "2"
