[package]
name = "ic_runtime"
description = "Interconnect's runtime-library"
version = "0.1.0"

rust-version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "sync"] }
parking_lot = { version = "0.12.5" }
pin-project-lite = { version = "0.2.11" }
zerocopy = { version = "0.8.33", features = ["derive"]}
munge = { version = "0.4.0"}

aes-gcm = { version = "0.10.3" }
aead = { version = "0.5.2" }
x25519-dalek = { version = "2.0.1" }
hkdf = "0.12.4"
sha2 = "0.10.9"

bincode =  { version = "2.0.1", features = ["serde", "derive"] }
serde = { version = "1.0.228", features = ["derive"] }